name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
        - name: Deploy to cPanel via SSH
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: 50.6.35.127
            username: xqbwngmy
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            passphrase: ${{ secrets.SSH_PASSWORD }}
            script: |
              cd public_html/testing
              git pull origin main